<script setup lang="ts">
import { marked } from 'marked'
import { CopyIcon, LinkIcon, SendIcon, ThumbUpIcon, UserIcon } from 'tdesign-icons-vue-next'
import type { UserMessage } from '../../types/user'
defineProps<{ messages: UserMessage[]; inputText: string; isSending: boolean; sourcePanelOpen: boolean; title: string; sourceCount: number }>()
const emit = defineEmits<{ (event: 'toggle-sources'): void; (event: 'update:input-text', value: string): void; (event: 'send'): void; (event: 'suggestion', value: string): void }>()
const renderMarkdown = (value: string) => marked.parse(value, { breaks: true }) as string
</script>
<template>
  <section class="chat-panel"><div class="chat-head"><div><div class="eyebrow">知识库咨询</div><h1>{{ title }}</h1></div><div class="chat-actions"><t-button variant="outline" size="small" @click="emit('toggle-sources')"><LinkIcon /><span class="source-toggle-label">{{ sourcePanelOpen ? '隐藏来源' : '查看来源' }}</span></t-button></div></div><div class="chat-scroll"><div v-if="messages.length === 0" class="empty-chat"><div class="empty-icon">工</div><h2>开始一次新的技术咨询</h2><p>从设备型号、故障代码或操作方法开始提问。</p></div><template v-else><div v-for="message in messages" :key="message.id" class="message" :class="message.role"><div class="message-avatar" :class="message.role"><UserIcon v-if="message.role === 'user'" /><span v-else>工</span></div><div class="message-body"><div class="message-meta"><strong>{{ message.role === 'user' ? '用户' : '工智库助手' }}</strong><span>{{ message.time }}</span><span v-if="message.role === 'assistant' && sourceCount" class="source-tag">基于 {{ sourceCount }} 个来源</span></div><div v-if="message.role === 'assistant'" class="markdown-content" v-html="renderMarkdown(message.content)"></div><div v-else class="user-text">{{ message.content }}</div><div v-if="message.streaming" class="typing-indicator"><i></i><i></i><i></i></div><div v-if="message.role === 'assistant' && !message.streaming" class="message-tools"><t-button variant="text" size="small"><CopyIcon />复制</t-button><t-button variant="text" size="small"><ThumbUpIcon />有帮助</t-button></div></div></div></template><div v-if="messages.length" class="suggestions"><span>你还可以问</span><button @click="emit('suggestion', 'HAK180 的日常维护有哪些注意事项？')">HAK180 的日常维护有哪些注意事项？</button><button @click="emit('suggestion', '转印压力应该如何设置？')">转印压力应该如何设置？</button></div></div><div class="composer-wrap"><div class="composer"><textarea :value="inputText" rows="1" placeholder="输入设备型号、故障代码或你的问题..." @input="emit('update:input-text', ($event.target as HTMLTextAreaElement).value)" @keydown.enter.exact.prevent="emit('send')"></textarea><div class="composer-bottom"><div class="composer-hints"><span class="hint-text">当前仅基于本地知识库回答</span></div><t-button theme="primary" :disabled="!inputText.trim() || isSending" @click="emit('send')"><SendIcon />发送</t-button></div></div><div class="privacy-note">工智库可能会产生不准确的信息，请结合设备手册进行确认</div></div></section>
</template>
