"""add library rules and import tasks

Revision ID: 4574bd21512a
Revises: b84f6c8d1e2a
Create Date: 2026-09-02 23:38:53.891194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4574bd21512a'
down_revision: Union[str, Sequence[str], None] = 'b84f6c8d1e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_import_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('current_step', sa.String(length=40), nullable=True),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('entity_result', sa.JSON(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['kb_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_id'], ['kb_library.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_import_task_document_created', 'kb_import_task', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_kb_import_task_library_status', 'kb_import_task', ['library_id', 'status'], unique=False)
    op.add_column('kb_document', sa.Column('deleted_by', sa.BigInteger(), nullable=True))
    op.add_column('kb_library', sa.Column('content_type', sa.String(length=20), server_default='general', nullable=False))
    op.add_column('kb_library', sa.Column('entity_recognition_mode', sa.String(length=20), server_default='disabled', nullable=False))
    op.add_column('kb_library', sa.Column('allowed_file_types', sa.JSON(), nullable=True))
    op.add_column('kb_library', sa.Column('max_file_size_mb', sa.Integer(), nullable=True))
    op.add_column('kb_library', sa.Column('max_document_count', sa.Integer(), nullable=True))
    op.add_column('kb_library', sa.Column('chunking_config', sa.JSON(), nullable=True))
    op.add_column('kb_library', sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False))
    op.add_column('kb_library', sa.Column('deleted_by', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_library', 'deleted_by')
    op.drop_column('kb_library', 'visibility')
    op.drop_column('kb_library', 'chunking_config')
    op.drop_column('kb_library', 'max_document_count')
    op.drop_column('kb_library', 'max_file_size_mb')
    op.drop_column('kb_library', 'allowed_file_types')
    op.drop_column('kb_library', 'entity_recognition_mode')
    op.drop_column('kb_library', 'content_type')
    op.drop_column('kb_document', 'deleted_by')
    op.drop_index('ix_kb_import_task_library_status', table_name='kb_import_task')
    op.drop_index('ix_kb_import_task_document_created', table_name='kb_import_task')
    op.drop_table('kb_import_task')
    # ### end Alembic commands ###
