"""add permission parent hierarchy

Revision ID: 653972cf4482
Revises: db65def443bc
Create Date: 2026-09-01 22:36:08.031176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653972cf4482'
down_revision: Union[str, Sequence[str], None] = 'db65def443bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_permission', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sys_permission_parent_id'), 'sys_permission', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'sys_permission', 'sys_permission', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_permission', type_='foreignkey')
    op.drop_index(op.f('ix_sys_permission_parent_id'), table_name='sys_permission')
    op.drop_column('sys_permission', 'parent_id')
    # ### end Alembic commands ###
