"""add status and soft delete to role and permission

Revision ID: db65def443bc
Revises: 20260831_0001
Create Date: 2026-09-01 18:33:57.555803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db65def443bc'
down_revision: Union[str, Sequence[str], None] = '20260831_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_permission', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('sys_permission', sa.Column('deleted_by', sa.BigInteger(), nullable=True))
    op.add_column('sys_permission', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sys_role', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('sys_role', sa.Column('deleted_by', sa.BigInteger(), nullable=True))
    op.add_column('sys_role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_role', 'deleted_at')
    op.drop_column('sys_role', 'deleted_by')
    op.drop_column('sys_role', 'status')
    op.drop_column('sys_permission', 'deleted_at')
    op.drop_column('sys_permission', 'deleted_by')
    op.drop_column('sys_permission', 'status')
    # ### end Alembic commands ###
